name: 🐞 Bug Report
title: '[bug] '
description: Report a Bug
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Friendly Reminder
        1. Please check existing [issues](https://github.com/LongQT-sea/BongoCat-English/issues) first.
        2. Please make sure you are using the [latest version](https://github.com/LongQT-sea/BongoCat-English/releases/latest).
        3. Please ensure the issue is not caused by other software.
        4. Please always be friendly and respectful. Thank you for your understanding and cooperation.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please describe the bug in detail and provide screenshots or videos to help us better understand the issue.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please list the detailed steps to reproduce the issue, including screenshots or videos.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the behavior you expected to occur.

  - type: textarea
    id: info
    attributes:
      render: text
      label: Software Information
      description: Please go to Preferences > About > About Software > Software Information and copy the software information.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Please provide any other relevant information about this issue to help us understand it more comprehensively.
