name: 💡 Feature Request
title: '[feat] '
description: Suggest an idea
labels: feature request
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the Problem
      description: Please clearly describe the specific problem this feature would solve.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe Your Desired Solution
      description: Please clearly describe the changes or improvements you expect.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions Considered
      description: Provide other alternative solutions you have considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Please provide any other relevant information about this issue to help us understand it more comprehensively.
